### ISSUE TITLE
Crash with small python font

### ISSUE THREAD

**Issue by M4xi1m3** [Omega-Numworks/Omega#198]
#### Describe the bug
When using small font, if you reach the bottom of the console (with prints for example), the OS crashes.

Back trace :
```
epsilon.bin: escher/src/table_view.cpp :121 : int TableView::ContentView::typeIndexFromSubviewIndex(int, int) const:  l'assertion « typeIndex < m_dataSource->reusableCellCount(type) » a échoué.

Program received signal SIGABRT, Aborted.
0x00007ffff7866f25 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7866f25 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff7850897 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff7850767 in __assert_fail_base.cold () from /usr/lib/libc.so.6
#3  0x00007ffff785f526 in __assert_fail () from /usr/lib/libc.so.6
#4  0x00005555555f49fe in TableView::ContentView::typeIndexFromSubviewIndex(int, int) const ()
#5  0x00005555555f4a2e in TableView::ContentView::subviewAtIndex(int) ()
#6  0x00005555555f8368 in View::subview(int) ()
#7  0x00005555555f4a6c in TableView::ContentView::layoutSubviews() ()
#8  0x00005555555f4ad2 in TableView::layoutSubviews() ()
#9  0x00005555555f26c1 in SelectableTableView::reloadData(bool) ()
#10 0x00005555557959d5 in Code::ConsoleController::autoImportScript(Code::Script, bool) ()
#11 0x0000555555797f3c in Code::MenuController::openConsoleWithScript(Code::Script) ()
#12 0x0000555555799b73 in Code::ScriptParameterController::handleEvent(Ion::Events::Event) ()
#13 0x00005555555ea7bd in App::processEvent(Ion::Events::Event) ()
#14 0x00005555555ebcaa in Container::dispatchEvent(Ion::Events::Event) ()
#15 0x00005555557bdac4 in AppsContainer::dispatchEvent(Ion::Events::Event) ()
#16 0x00005555555f1026 in RunLoop::step() ()
#17 0x00005555555f1064 in RunLoop::runWhile(bool (*)(void*), void*) ()
#18 0x00005555557bdc94 in AppsContainer::run() ()
#19 0x00005555555e7f9f in main ()
```
(Wasn't able to get a more detailed back trace due to #1276)

#### Environment
 - Omega Version: latest dev (587b6ee)
 - Tested on linux simulator, n0110 and n0100.

**Comment by quentinguidee** [comment]
Closed by #199
