### ISSUE TITLE
Crashes pkg installer on Android 6

### ISSUE THREAD

**Issue by ElongatedVeggie** [Omega-Numworks/Omega#578]
**Describe the bug**
When installing the apk, it crashes the installer. 

**To Reproduce**
1. Download the apk (1.23.0 and 1.22.1, as noted are same files and the crashes are the same)
2. Click on the apk to install
3. Enjoy the crash

**Expected behavior**
To not crash my installer 

Logcat:

```
FATAL EXCEPTION: main
Process: com.google.android.packageinstaller, PID: 29245
java.lang.OutOfMemoryError: Failed to allocate a 268435468 byte allocation with 16925764 free bytes and 231MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1080)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2738)
	at android.content.res.Resources.loadDrawable(Resources.java:2643)
	at android.content.res.Resources.getDrawable(Resources.java:833)
	at android.content.res.Resources.getDrawable(Resources.java:786)
	at com.android.packageinstaller.PackageUtil.getAppSnippet(PackageUtil.java:193)
	at com.android.packageinstaller.PackageInstallerActivity.onCreate(PackageInstallerActivity.java:541)
	at android.app.Activity.performCreate(Activity.java:6272)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
	at android.app.ActivityThread.access$900(ActivityThread.java:157)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5525)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```
Android: Android 6
Phone: LG G4
Apk version: 1.23.0 and 1.22.1
RAM: 3gb in total, ~1-1.5 gb free when installing

**Additional information:**

I am not using any 3rd party installer (if that is even possible). Everything is stock Android provided by LG.

**Comment by lemoustachu** [comment]
It seems that you are running out of memory to do this operation. Maybe try to restart your phone and try again.

**Comment by ElongatedVeggie** [comment]
Sorry for the disappearance. I have been getting the same error for a few months now regardless whether it was after a reboot or when all apps are running in the background. I noted the RAM usage down there and how much it was free before starting the installation. Just to be sure, I rebooted right now and tried to install but I get the same crash.

**Comment by lemoustachu** [comment]
Ok strange bug
